name: Run Discord Bot

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Write application.yml
        run: |
          echo "discord:\n  token: '${{ secrets.DISCORD_TOKEN }}'\n  channel_id: '${{ secrets.DISCORD_CHANNEL_ID }}'" > application.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py holidays pyyaml

      - name: Run script
        run: python main.py
